version: 2.1

orbs:
  android: circleci/android@2.2.0
  ruby: circleci/ruby@2.0.0

jobs:
  unit-test-non-compose:
    docker:
      - image: cimg/ruby:2.7.2
      - image: cimg/openjdk:11.0
      - image: cimg/android:2023.02
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    steps:
      - checkout
      - ruby/install-deps
      - android/restore-gradle-cache
      - run:
          name: Install Fastlane
          command: bundle install --path vendor
      - run: |
          javac --version
          bundle exec fastlane test_all

workflows:
  test:
    jobs:
      - unit-test-non-compose