version: 2.1

executors:
  openjdk11:


jobs:
  unit-test-non-compose:
    docker:
#      - image: cimg/ruby:2.7.2
      - image: cimg/openjdk:19.0.2-node
    steps:
      - checkout
#      - ruby/install-deps
      - run: java --version
      - run:
          name: Install Fastlane
          command: bundle install --path vendor
      - run: |
          bundle exec fastlane test_all

workflows:
  test:
    jobs:
      - unit-test-non-compose