version: 2.1

jobs:
  unit-test-non-compose:
    macos:
    steps:
      - checkout
      - run: java --version
      - run:
          name: Install Fastlane
          command: bundle install --path vendor
      - run: |
          bundle exec fastlane test_all

workflows:
  test:
    jobs:
      - unit-test-non-compose