version: 2.1

jobs:
  unit-test-non-compose:
    executor: android/android
    steps:
      - checkout
      - run: java --version
      - run: bundle install --path vendor
      - run: bundle exec fastlane test_all


workflows:
  test:
    jobs:
      - unit-test-non-compose