version: 2.1

orbs:
  android: circleci/android@2.2.0
  ruby: circleci/ruby@2.0.0

jobs:
  unit-test-non-compose:
    docker:
      - image: cimg/ruby:2.7.2
#      - image: cimg/android:2023.02
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install Fastlane
          command: |
            mkdir vendor
            bundle install --path vendor
      - run: bundle exec fastlane test_all


workflows:
  test:
    jobs:
      - unit-test-non-compose